### ISSUE TITLE
Inconsistency issue - geo_performance 

### ISSUE THREAD

**Issue by yershovkiril** [google/app-reporting-pack#2]
https://github.com/google/app-reporting-pack/blob/9821415aafccb90152ffdad2b9a75ce5599707ac/bq_queries/geo_performance.sql#L47

this join brings duplicates and inconsistency in metrics, in particular costs value

**Comment by AndreyMarkinPPC** [comment]
Thanks for spotting this! Fixed in [Remove duplicates from geo_performance table](https://github.com/google/app-reporting-pack/commit/8a25d3cff24fc3db271ec15b1084538fc91ecc63).
