### ISSUE TITLE
arp.ocid_mapping is missing

### ISSUE THREAD

**Issue by kohry** [google/app-reporting-pack#23]
Hello, 

With the newly launched branch (1.3.1) I can see that 'arp.ocid_maaping' is not generated from the script. 
When running asset_conversion_split.sql / asset_performance / performance_grouping_history and other important tables, the same errors keep poping with themessage, 

'arp.ocid_mapping was not found in location US'

**Comment by AndreyMarkinPPC** [comment]
Hi,

I've tried to reproduce this error both on the latest commit of main branch as fell as running code in `ghcr.io/google/app-reporting-pack:1.3.1` container - `ocid_mapping` was always generated.
Could you try pulling the latest changes and try running the code manually `bash app/run-local.sh`?

**Comment by AndreyMarkinPPC** [comment]
Error should be resolved in release 1.4.0 - https://github.com/google/app-reporting-pack/tree/1.4.0
